services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysql -u root -p$$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES;"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - MYSQL_NAME=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
